sdm: Define DRM_MODE_FLAG_SUPPORTS_RGB for libsdmcore
* Fixup Missing Definition

 error: ^[[0m^[[1muse of undeclared identifier 'DRM_MODE_FLAG_SUPPORTS_RGB'^[[0m
  if (mode.flags & DRM_MODE_FLAG_SUPPORTS_RGB) {
                   ^

Change-Id: I6fb011cda1cdf85e5690a3038999050b7dd0a682